{% set version = '0.4-5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jmbayes2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/JMbayes2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/JMbayes2/JMbayes2_{{ version }}.tar.gz
  sha256: 27b51c6b075bfc90421809e369f317dcdad5b7cf509a925c29c93b7ef2b8ae61

build:
  merge_build_host: True           # [win]
  number: 0
  skip: True  # [r_base == "4.1"]
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'                    # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - llvm-openmp  # [osx]
    - libcxx  # [osx]
    - libgomp  # [linux]
  host:
    - r-base
    - r-glmmadaptive
    - r-rcpp
    - r-rcpparmadillo
    - r-coda
    - r-ggplot2
    - r-gridextra
    - r-matrixstats
    - r-nlme
    - r-parallelly
    - r-survival
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-glmmadaptive
    - r-rcpp
    - r-rcpparmadillo
    - r-coda
    - r-ggplot2
    - r-gridextra
    - r-matrixstats
    - r-nlme
    - r-parallelly
    - r-survival
    - libcxx   # [osx]

test:
  commands:
    - $R -e "library('JMbayes2')"           # [not win]
    - "\"%R%\" -e \"library('JMbayes2')\""  # [win]

about:
  home: https://drizopoulos.github.io/JMbayes2/, https://github.com/drizopoulos/JMbayes2
  license: GPL-3.0-or-later
  summary: Fit joint models for longitudinal and time-to-event data under the Bayesian approach.
    Multiple longitudinal outcomes of mixed type (continuous/categorical) and multiple
    event times (competing risks and multi-state processes) are accommodated. Rizopoulos
    (2012, ISBN:9781439872864).
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: JMbayes2
# Type: Package
# Title: Extended Joint Models for Longitudinal and Time-to-Event Data
# Version: 0.4-5
# Authors@R: c(person("Dimitris", "Rizopoulos", email = "d.rizopoulos@erasmusmc.nl", role = c("aut", "cre"), comment = c(ORCID = '0000-0001-9397-0900')), person("Grigorios", "Papageorgiou", email = "g.papageorgiou@erasmusmc.nl", role = "aut"), person("Pedro", "Miranda Afonso", email = "p.mirandaafonso@erasmusmc.nl", role = "aut"))
# Maintainer: Dimitris Rizopoulos <d.rizopoulos@erasmusmc.nl>
# Date: 2023-06-23
# BugReports: https://github.com/drizopoulos/JMbayes2/issues
# Description: Fit joint models for longitudinal and time-to-event data under the Bayesian approach. Multiple longitudinal outcomes of mixed type (continuous/categorical) and multiple event times (competing risks and multi-state processes) are accommodated. Rizopoulos (2012, ISBN:9781439872864).
# Suggests: lattice, knitr, rmarkdown, pkgdown
# Encoding: UTF-8
# Depends: survival, nlme, GLMMadaptive, splines
# Imports: coda, Rcpp, parallel, parallelly, matrixStats, ggplot2, gridExtra
# LinkingTo: Rcpp, RcppArmadillo
# LazyLoad: yes
# LazyData: yes
# License: GPL (>= 3)
# URL: https://drizopoulos.github.io/JMbayes2/, https://github.com/drizopoulos/JMbayes2
# NeedsCompilation: yes
# Packaged: 2023-06-26 11:50:46 UTC; drizo
# Author: Dimitris Rizopoulos [aut, cre] (<https://orcid.org/0000-0001-9397-0900>), Grigorios Papageorgiou [aut], Pedro Miranda Afonso [aut]
# Repository: CRAN
# Date/Publication: 2023-06-26 13:30:05 UTC
